### ISSUE TITLE
How to effectively produce videos

### ISSUE THREAD

**Issue by ghost** [humanetech-community/awareness-program#15] opened 2018-10-10 08:51 UTC
There has been a debate brewing on how to produce videos with maximum spread and impact, while keeping costs low.

In this thread, we discuss the practicalities of three proposed modes of production, namely:

- In-house (crowdsourced)
- Professional studios - see [template RFP here](https://github.com/humanetech-community/humanetech-community-awareness/issues/14)
- Visual arts academies

Each option has its pros and cons. Most important is to get the job done, quickly and with high quality.

Here we discuss all available options, without making judgement on whether one option is better than the others.

**Comment by georgeshk** [comment] 2018-10-10 08:56
Hi @patmatsu

We all await your ideas here on discussions with Visual Arts Academies.

**Comment by patmatsu** [comment] 2018-10-11 22:20
Just saw my friend Noah, and our conversation went well. He is going to put me in touch with Grace, his friend in California. I am going to describe our project to her and see if she wants to bid on it. I will ask her to break down her fee so that we can see what is involved and how much each step costs.

**Comment by georgeshk** [comment] 2018-10-11 22:57
> I am going to describe our project to her

Just to confirm, which "project" are you referring to? Is it the whole Reality Shock campaign, or the first video, i.e. "a coffee place"?

**Comment by patmatsu** [comment] 2018-10-12 00:31
Sorry to not be clear. I will write her about whichever project we--or you--want her to consider first.

**Comment by georgeshk** [comment] 2018-10-12 00:43
> I will write her about whichever project we--or you--want her to consider first.

Let me know if you agree with this approach: your discussions with her would give us a glimpse into what to expect from video studios (first reactions, expectations, budget ballparks, etc). Hence it is ok to discuss a variety of projects at once, or choose one as an example (maybe more practical).

You can refer to the draft RFP. Say you were to write her an email, you could attach the RFP (hmmm...maybe need to reformat to Word, copy paste may not work) for the first video ("a coffee place"), although this one most likely would be produced in Europe.

In my view, this would look more professional, and more likely to get attention.

**Comment by georgeshk** [comment] 2018-10-12 00:44
As you probably saw, the RFP forms part of a separate issue.

**Comment by patmatsu** [comment] 2018-10-12 04:53
OK, I agree and will do as you suggest. Thank you :-)

**Comment by georgeshk** [comment] 2018-10-12 04:58
Also, I have not changed the original draft after @aschrijver commented on the partnership aspect. Kindly change the word "publicity" to "special credits". Thanks!

**Comment by patmatsu** [comment] 2018-10-12 05:08
Thank you for the reminder. Will do!

**Comment by patmatsu** [comment] 2018-10-14 19:15
@georgeshk and @aschrijver, please take a look at this draft. You'll see it's in two parts: one describing the overall campaign, and one describing the "Coffee Place" project. I had several questions, which I tried to answer by supplying placeholder
[Reality Shock Campaign.docx](https://github.com/humanetech-community/humanetech-community-awareness/files/2476765/Reality.Shock.Campaign.docx)
 text. You'll see this as soon as you start reading. We need to agree on phrasing, content, etc.

**Comment by patmatsu** [comment] 2018-10-14 19:16
@georgeshk and @aschrijver, please take a look at this draft. You'll see it's in two parts: one describing the overall campaign, and one describing the "Coffee Place" project. I had several questions, which I tried to answer by supplying placeholder text. You'll see this as soon as you start reading. We need to agree on phrasing, content, etc.

[Reality Shock Campaign.docx](https://github.com/humanetech-community/humanetech-community-awareness/files/2476769/Reality.Shock.Campaign.docx)

**Comment by georgeshk** [comment] 2018-10-15 00:07
@patmatsu

Not sure if I am seeing the entire document (viewing it on my phone right now), but it seems you have taken out the cover letter, as well as a number of appendices. Not sure why. Sending a fully detailed and professional RFP would be better received.

**Comment by georgeshk** [comment] 2018-10-15 00:39
Did you see the original draft RFP? Here it is: https://github.com/humanetech-community/humanetech-community-awareness/issues/14

**Comment by georgeshk** [comment] 2018-10-15 01:13
@patmatsu 

For your convenience, I converted the RFP to Word format. See the [file here ](#14 )

**Comment by patmatsu** [comment] 2018-10-15 03:44
It is hard for me to follow all that is happening here and to remember the structure. What you produced is much better. Would you be averse to my sharing it with the faculty member of the Academy of Creative Media whom I know?

**Comment by georgeshk** [comment] 2018-10-15 04:05
> It is hard for me to follow all that is happening here and to remember the structure. 

Thanks for this feedback. I will update the first post here to refer to the draft RFP, which may help other members as well.

> Would you be averse to my sharing it with the faculty member of the Academy of Creative Media whom I know?

Personally, not at all. It is not confidential, and thanks to your initiative, we may get very useful feedback so we can improve our approach to videographers.

**Comment by georgeshk** [comment] 2018-10-16 02:51
Hi @patmatsu

Any update to offer on your approaches to visual arts academies and this one specific production studio?

**Comment by patmatsu** [comment] 2018-10-16 05:03
Nothing to report yet. Apologies.

**Comment by georgeshk** [comment] 2018-10-16 05:10
> Nothing to report yet. Apologies.

No need for apologies! We should be patient, these things take time.

**Comment by patmatsu** [comment] 2018-10-16 18:47
>Any update to offer on your approaches to visual arts academies and this one specific production studio?

@georgeshk, I referred to this part of our conversation in a message to @aschrijver, and he had no knowledge of it. Can you please not resolve things like this until we are sure he has seen them? Many thanks.

**Comment by georgeshk** [comment] 2018-10-16 23:14
@patmatsu

> @georgeshk, I referred to this part of our conversation in a message to @aschrijver, and he had no knowledge of it. Can you please not resolve things like this until we are sure he has seen them? Many thanks.

Not sure what you mean by "resolving things". I was merely asking if you had any update on your plans to approach a few people about this.

Also note that this is a community, where everyone is free to suggest ideas or actions. I was not forcing or directing you to do anything. Likewise, @aschrijver is very busy facilitating the projects of this community. While he is duly highly respected, he is not the CEO of our organization, i.e. an authority who decides what to do or not to do.

Therefore, if you feel (as I thought you did) that it would be a good idea to contact certain people, and I agree with you, and nobody is strongly against it, I am not sure what the problem is.

**Comment by patmatsu** [comment] 2018-10-16 23:34
Sorry about this misunderstanding, @georgeshk. @aschrijver and I talked about it. I made an assumption that was wrong.

Will be more tactful and diplomatic in the future, I assure you.

**Comment by aschrijver** [comment] 2018-10-17 08:14
The resolving was my doing. My apologies! I forgot to mention it in my Campaigners group post. I was only trying to collapse the comments that were not relevant to newcomes (because handled, off-topic), so as not to scare people away. I'll get my hands off it, and first communicate more on project plans on the forum.

**Comment by MelodyLiuNa** [comment] 2018-11-17 22:18
Hi everyone, 

I'm a new member of the community, also a videographer (2D and 360). I used to work for media investment agencies so have grown to be very concerned about what tech is doing to us (seeing what's happening behind the scene). Having read Tristan's articles on Medium, I wanted to contribute. Let me know if there's anything I could do to help!

Melody Liu
Reel: www.melodyliuna.com
Emails: 
nihao@melodyliuna.com
melody@yooteki.com

**Closed** 2019-04-27 08:56 UTC
Labels: work-methods
